services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: chinmay
      POSTGRES_PASSWORD: test@123
    ports:
      - "5432:5432"


  app:
    build: .
    container_name: spring_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myappdb
      SPRING_DATASOURCE_USERNAME: chinmay
      SPRING_DATASOURCE_PASSWORD: test@123
    ports:
      - "9090:9090"

volumes:
  postgres_data:
