server:
  port: 4041

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

#  profiles:
#    active: dev
  config:
    import: optional:configserver:http://localhost:8889

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-7637524.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oav799z0bZZiHQob697
            client-secret: PirxVVyq-icERT2pz6wjKlFZ2tKR5OwkowQoFbKvi_rcQYHBUBvPAK03IqmoJNsf
        provider:
          okta:
            issuer-uri: https://integrator-7637524.okta.com/oauth2/default




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:4000/eureka
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakerevents,circuitbreakers
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true


resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failureRateThreshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 1200ms

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

okta:
  oauth2:
    issuer: https://integrator-7637524.okta.com/oauth2/default
    audience: api://default